# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  fastlane_dir = "fastlane/"
  artifacts_dir = fastlane_dir + "artifacts/"
  beta_dir = artifacts_dir + "beta/"
  package_dir = artifacts_dir + "package/"
  original_profile_dir = '~/Library/MobileDevice/Provisioning\ Profiles/'
  xcode_server_profile_dir = '/Library/Developer/XcodeServer/ProvisioningProfiles/'
  derived_data_path = artifacts_dir + "derivedData"
  test_output_dir = artifacts_dir + "test/"
  gcovr_out_path = artifacts_dir + "coverage.xml"
  oclint_out_path = artifacts_dir + "oclint.xml"
  compilation_database_path = test_output_dir + "report.json-compilation-database"
  sonar_configuration_path = artifacts_dir + "sonar.properties"
  filter_pattern = '.*Pod/.*'
  spec_file = '../../ineo/Netmera.podspec'

  FileUtils.rm_rf(artifacts_dir)
  FileUtils.mkdir_p(beta_dir)
  FileUtils.mkdir_p(package_dir)

  def send_via_sftp(local_path, remote_path, create_link=false)
    require 'net/sftp'
    Net::SFTP.start('release.netmera.com', ENV['NetmeraSFTPUser'], :password => ENV['NetmeraSFTPPassword'], :port => 3053) do |sftp|
      sftp.upload!(local_path.to_path, remote_path.to_path)
      if create_link
        link_path = (remote_path.dirname + "latest#{remote_path.extname}").to_path
        sftp.remove!(link_path)
        sftp.symlink!(remote_path.to_path, link_path)
      end

    end
  end
  
    lane :beta_enterprise do
    prepare_enterprise_credentials
    gym(
      scheme: 'iNeoX',
      output_directory: beta_dir,
      xcargs: "PROVISIONING_PROFILE=#{lane_context[SharedValues::SIGH_UDID]}",
      export_options: {
      method: "enterprise",
      manifest: {
        appURL: "https://s3-eu-west-1.amazonaws.com/use-case/ElevateDemoApps/IneoNova/iNeo.ipa",
        displayImageURL: "https://s3-eu-west-1.amazonaws.com/use-case/ElevateDemoApps/icon180.png",
        fullSizeImageURL: "https://s3-eu-west-1.amazonaws.com/use-case/ElevateDemoApps/icon180.png",
        },
      }
    )
  end
  
  lane :prepare_development_credentials do
    match()
  end

  lane :prepare_production_credentials do
    match(type: "adhoc")
  end
  
  lane :prepare_enterprise_credentials do
  match(type: "enterprise")
#    sync_code_signing(type: "enterprise", readonly: true)
  end
  
  lane :carthage_beta do
  
  carthage(
    # frameworks: ['Netmera-framework'],   # Specify which frameworks to archive (only for the archive command)
    # output: 'Netmera.framework.zip',      # Specify the output archive name (only for the archive command)
    command: 'build',       # One of: build, bootstrap, update, archive. (default: bootstrap)
    # dependencies: ["MMWormhole", "FMDB", "UICKeyChainStore", "AFNetworking/NSURLSession"],# Specify which dependencies to update or build (only for update, build and bootstrap commands)
    # use_ssh: false,   # Use SSH for downloading GitHub repositories.
    # use_submodules: false,      # Add dependencies as Git submodules.
    # use_binaries: true,         # Check out dependency repositories even when prebuilt frameworks exist
    # no_build: false,  # When bootstrapping Carthage do not build
    no_skip_current: true,     # Don't skip building the current project (only for frameworks)
    verbose: true,   # Print xcodebuild output inline
    platform: "iOS",  # Define which platform to build for (one of ‘all’, ‘Mac’, ‘iOS’, ‘watchOS’, ‘tvOS‘, or comma-separated values of the formers except for ‘all’)
    configuration: "Release",   # Build configuration to use when building
    # cache_builds: true,         # By default Carthage will rebuild a dependency regardless of whether its the same resolved version as before.
    # toolchain: "com.apple.dt.toolchain.Swift_2_3",  # Specify the xcodebuild toolchain
    # new_resolver: false,        # Use the new resolver to resolve depdendency graph
    # log_path: "carthage.log"    # Path to the xcode build output
  )

  carthage(
    frameworks: ['Netmera'],   # Specify which frameworks to archive (only for the archive command)
    output: 'Netmera.framework.zip',      # Specify the output archive name (only for the archive command)
    command: 'archive',       # One of: build, bootstrap, update, archive. (default: bootstrap)
  )
  end
  
  
  
  lane :deliver_internal_framework do
    zip_path, spec_path = generate_internal_framework
    send_via_sftp(zip_path, Pathname.new('/nmsdk/test/ios') + zip_path.basename, true)
    sh "bundle exec pod repo push --verbose inomera #{spec_path}"
  end

  lane :deliver_framework do
    zip_path, spec_path = generate_framework
    send_via_sftp(zip_path, Pathname.new('/nmsdk/release/ios') + zip_path.basename)
  end

  lane :release_framework do
    zip_path, spec_path = generate_framework
    send_via_sftp(zip_path, Pathname.new('/nmsdk/release/ios') + zip_path.basename, true)
    sh "pwd"
    sh "pod trunk push --verbose #{spec_path}"
  end

  lane :generate_internal_framework do
    require 'cocoapods-core'
    spec = Pod::Specification.from_file(spec_file)
    package_name = "#{spec.name}-#{spec.version}"
    framework_dir = package_dir + "#{package_name}/"
    generated_spec_path = framework_dir + "#{spec.name}.podspec"
    framework_source = {:http => "https://release.netmera.com/test/ios/#{spec.version}.zip"}
    sh "bundle exec pod package --verbose --embedded --force --subspecs=#{spec.subspecs.map(&:base_name).join(',')} #{spec_file} '#{framework_source}'"
    sh "mv #{package_name} #{package_dir}"

    # zip framework
    sh "cd #{framework_dir} && zip -r -X -y #{spec.version}.zip #{spec.available_platforms.map(&:name).join(' ')}"
    sh "mv #{framework_dir}#{spec.version}.zip #{package_dir}"

    # return zip path
    [Pathname.new("#{package_dir}#{spec.version}.zip"), Pathname.new(generated_spec_path)]
  end

  lane :generate_framework do
    require 'cocoapods-core'
    spec = Pod::Specification.from_file(spec_file)
    package_name = "#{spec.name}-#{spec.version}"
    framework_dir = package_dir + "#{package_name}/"
    generated_spec_path = framework_dir + "#{spec.name}.podspec"
    framework_source = {:http => "https://release.netmera.com/release/ios/#{spec.version}.zip"}
    sh "bundle exec pod package --verbose --embedded --force --subspecs=#{spec.subspecs.map(&:base_name).join(',')} #{spec_file} '#{framework_source}'"
    sh "mv #{package_name} #{package_dir}"

    # zip framework
    sh "cd #{framework_dir} && zip -r -X -y #{spec.version}.zip #{spec.available_platforms.map(&:name).join(' ')}"
    sh "mv #{framework_dir}#{spec.version}.zip #{package_dir}"

    # return zip path
    [Pathname.new("#{package_dir}#{spec.version}.zip"), Pathname.new(generated_spec_path)]
  end
  
end
