# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  fastlane_dir = "fastlane/"
  artifacts_dir = fastlane_dir + "artifacts/"
  beta_dir = artifacts_dir + "beta/"
  package_dir = artifacts_dir + "package/"
  original_profile_dir = '~/Library/MobileDevice/Provisioning\ Profiles/'
  xcode_server_profile_dir = '/Library/Developer/XcodeServer/ProvisioningProfiles/'
  derived_data_path = artifacts_dir + "derivedData"
  test_output_dir = artifacts_dir + "test/"
  gcovr_out_path = artifacts_dir + "coverage.xml"
  oclint_out_path = artifacts_dir + "oclint.xml"
  compilation_database_path = test_output_dir + "report.json-compilation-database"
  sonar_configuration_path = artifacts_dir + "sonar.properties"
  filter_pattern = '.*Pod/.*'
  spec_file = '../../ineo/Netmera.podspec'

#FileUtils.rm_rf(artifacts_dir)
  FileUtils.mkdir_p(beta_dir)
  FileUtils.mkdir_p(package_dir)

  def send_via_sftp(local_path, remote_path, create_link=false)
    require 'net/sftp'
    Net::SFTP.start('release.netmera.com', ENV['NetmeraSFTPUser'], :password => ENV['NetmeraSFTPPassword'], :port => 3053) do |sftp|
      sftp.upload!(local_path.to_path, remote_path.to_path)
      if create_link
        link_path = (remote_path.dirname + "latest#{remote_path.extname}").to_path
        sftp.remove!(link_path)
        sftp.symlink!(remote_path.to_path, link_path)
      end

    end
  end
  
    lane :beta_enterprise do
    prepare_enterprise_credentials
    gym(
      scheme: 'iNeoX',
      output_directory: beta_dir,
      xcargs: "PROVISIONING_PROFILE=#{lane_context[SharedValues::SIGH_UDID]}",
      export_options: {
      method: "enterprise",
      manifest: {
        appURL: "https://s3-eu-west-1.amazonaws.com/use-case/ElevateDemoApps/IneoNova/iNeoX.ipa",
        displayImageURL: "https://s3-eu-west-1.amazonaws.com/use-case/ElevateDemoApps/icon180.png",
        fullSizeImageURL: "https://s3-eu-west-1.amazonaws.com/use-case/ElevateDemoApps/icon180.png",
        },
      }
    )
  end
  
  lane :prepare_development_credentials do
    match()
  end

  lane :prepare_production_credentials do
    match(type: "adhoc")
  end
  
  lane :prepare_enterprise_credentials do
      match(git_url: "https://github.com/muhammedkilinc/netmera-certificates.git", type: "enterprise", app_identifier: ["com.inomera.iNeo", "com.inomera.iNeo.NotificationService", "com.inomera.iNeo.NotificationContent"], team_id: "95N24W2PH8")
  end
  
  lane :carthage_beta do
  
  carthage(
    # frameworks: ['Netmera-framework'],   # Specify which frameworks to archive (only for the archive command)
    # output: 'Netmera.framework.zip',      # Specify the output archive name (only for the archive command)
    command: 'build',       # One of: build, bootstrap, update, archive. (default: bootstrap)
    # dependencies: ["MMWormhole", "FMDB", "UICKeyChainStore", "AFNetworking/NSURLSession"],# Specify which dependencies to update or build (only for update, build and bootstrap commands)
    # use_ssh: false,   # Use SSH for downloading GitHub repositories.
    # use_submodules: false,      # Add dependencies as Git submodules.
    # use_binaries: true,         # Check out dependency repositories even when prebuilt frameworks exist
    # no_build: false,  # When bootstrapping Carthage do not build
    no_skip_current: true,     # Don't skip building the current project (only for frameworks)
    verbose: true,   # Print xcodebuild output inline
    platform: "iOS",  # Define which platform to build for (one of ‘all’, ‘Mac’, ‘iOS’, ‘watchOS’, ‘tvOS‘, or comma-separated values of the formers except for ‘all’)
    configuration: "Release",   # Build configuration to use when building
    # cache_builds: true,         # By default Carthage will rebuild a dependency regardless of whether its the same resolved version as before.
    # toolchain: "com.apple.dt.toolchain.Swift_2_3",  # Specify the xcodebuild toolchain
    # new_resolver: false,        # Use the new resolver to resolve depdendency graph
    # log_path: "carthage.log"    # Path to the xcode build output
  )

  carthage(
    frameworks: ['Netmera'],   # Specify which frameworks to archive (only for the archive command)
    output: 'Netmera.framework.zip',      # Specify the output archive name (only for the archive command)
    command: 'archive',       # One of: build, bootstrap, update, archive. (default: bootstrap)
  )
  end
  
  
  
  lane :deliver_internal_framework do
    zip_path, spec_path = generate_internal_framework
    send_via_sftp(zip_path, Pathname.new('/nmsdk/test/ios') + zip_path.basename, true)
    sh "bundle exec pod repo push --verbose inomera #{spec_path}"
  end

  lane :deliver_framework do
    zip_path, spec_path = generate_framework
    send_via_sftp(zip_path, Pathname.new('/nmsdk/release/ios') + zip_path.basename)
  end

  lane :release_framework do
    zip_path, spec_path = generate_framework
    send_via_sftp(zip_path, Pathname.new('/nmsdk/release/ios') + zip_path.basename, true)
    sh "pwd"
    sh "pod trunk push --verbose #{spec_path}"
  end

  lane :generate_internal_framework do
    require 'cocoapods-core'
    spec = Pod::Specification.from_file(spec_file)
    package_name = "#{spec.name}-#{spec.version}"
    framework_dir = package_dir + "#{package_name}/"
    generated_spec_path = framework_dir + "#{spec.name}.podspec"
    framework_source = {:http => "https://release.netmera.com/test/ios/#{spec.version}.zip"}
    sh "bundle exec pod package --verbose --embedded --force --subspecs=#{spec.subspecs.map(&:base_name).join(',')} #{spec_file} '#{framework_source}'"
    sh "mv #{package_name} #{package_dir}"

    # zip framework
    sh "cd #{framework_dir} && zip -r -X -y #{spec.version}.zip #{spec.available_platforms.map(&:name).join(' ')}"
    sh "mv #{framework_dir}#{spec.version}.zip #{package_dir}"

    # return zip path
    [Pathname.new("#{package_dir}#{spec.version}.zip"), Pathname.new(generated_spec_path)]
  end

  lane :generate_framework do
    require 'cocoapods-core'
    spec = Pod::Specification.from_file(spec_file)
    package_name = "#{spec.name}-#{spec.version}"
    framework_dir = package_dir + "#{package_name}/"
    generated_spec_path = framework_dir + "#{spec.name}.podspec"
    framework_source = {:http => "https://release.netmera.com/release/ios/#{spec.version}.zip"}
    sh "bundle exec pod package --verbose --embedded --force --subspecs=#{spec.subspecs.map(&:base_name).join(',')} #{spec_file} '#{framework_source}'"
    sh "mv #{package_name} #{package_dir}"

    # zip framework
    sh "cd #{framework_dir} && zip -r -X -y #{spec.version}.zip #{spec.available_platforms.map(&:name).join(' ')}"
    sh "mv #{framework_dir}#{spec.version}.zip #{package_dir}"

    # return zip path
    [Pathname.new("#{package_dir}#{spec.version}.zip"), Pathname.new(generated_spec_path)]
  end
  
lane :upload_beta_amazon do

aws_s3(
# All of these are used to make Shenzhen's `ipa distribute:s3` command
access_key: ENV['S3_ACCESS_KEY'],               # Required from user (unless using aws_profile).
secret_access_key: ENV['S3_SECRET_ACCESS_KEY'], # Required from user (unless using aws_profile).
# aws_profile: ENV['AWS_PROFILE'],                 # Required from user (unless using access_key and secret_access_key)
bucket: ENV['S3_BUCKET'],                       # Required from user.
region: ENV['S3_REGION'],                       # Required from user.
# acl: ENV['S3_ACL'],                             # Optional - defaults to 'public-read'
# server_side_encryption: ENV['S3_SERVER_SIDE_ENCRYPTION'] # Optional

# endpoint: 'https://s3-eu-west-1.amazonaws.com', # Optional, for buckets that require a specific endpoint
ipa: 'fastlane/artifacts/beta/iNeoX.ipa',                             # Required (if not uploading an APK).
dsym: 'fastlane/artifacts/beta/iNeoX.app.dSYM.zip',                   # Optional if you use `ipa` to build.
# app_directory: 'ios',                # Optional but nice if you want to put multiple apps in same bucket
path: 'v{CFBundleShortVersionString}_b{CFBundleVersion}/', # This is actually the default.
upload_metadata: true,                          # Upload version.json, plist and HTML. Set to false to skip uploading of these files.
version_file_name: 'app_version.json',          # Name of the file to upload to S3. Defaults to 'version.json'
version_template_path: 'path/to/erb'            # Path to an ERB to configure the structure of the version JSON file
)
end

desc 'Release new pod version'
lane :release_pod do |options|
  target_repo    = options[:repo]
  target_project = options[:project]
  target_version = options[:version]
  target_desc    = options[:desc]
  spec_path      = "#{target_project}.podspec"

  if target_project.nil? || target_project.empty? || target_version.nil? || target_version.empty?
    UI.message("❌ Project name and version number are required parameters")
    exit
  end

  UI.message("👉 Start release lib #{target_project} new version #{target_version}")

  git_pull
  ensure_git_branch
  version_bump_podspec(path: spec_path, version_number: target_version)
  git_add(path: '.')
  begin
    if target_desc.nil? || target_desc.empty?
      git_commit(path: '.', message: "release #{target_version}")
    else
      git_commit(path: '.', message: target_desc)
    end
  rescue
    error_message = "#{$!}"
    UI.message("⚠️ commit error:#{error_message}")
    unless error_message.include?("nothing to commit, working directory clean")
      exit
    end
    UI.message("The local code has committed, skip the commit step!")
  end
  push_to_git_remote
  if git_tag_exists(tag: target_version)
      UI.message("Tag #{target_version} already exists, then, delete it! 💥")
      remove_git_tag(tag: target_version)
  end
  add_git_tag(tag: target_version)
  push_git_tags
  pod_lib_lint(allow_warnings: true)
  if target_repo
    pod_push(path: spec_path, repo: target_repo, allow_warnings: true)
    UI.message("Release lib #{target_project} new version #{target_version} to repo #{target_repo} Successfully! 🎉 ")
  else
    pod_push(path: spec_path, allow_warnings: true)
    UI.message("Release lib #{target_project} new version #{target_version} to CocoaPods/Specs Successfully! 🎉 ")
  end
end
end
